### ISSUE TITLE
[BUG] Cron error

### ISSUE THREAD

**Issue by tuuni** [nathan-fiscaletti/TeamSpeak-Integration-Issue-Tracker#10]
**Describe the bug**

When enabling the app in invision, then it throws task error ever time (every minute) cron execute.
*Using latest version 2.0.6

`DateInterval::__construct(): Unknown or bad format (30)

#0 /htdocs/system/Task/Task.php(401): DateInterval->__construct('30')
#1 /htdocs/system/Task/Task.php(199): IPS\_Task->unlock()
#2 /htdocs/applications/core/interface/task/task.php(54): IPS\_Task::queued()
#3 {main}`

**Comment by nathan-fiscaletti** [comment]
See #12 for information on how to temporarily resolve this. A fix should be coming in the next update.

**Comment by nathan-fiscaletti** [comment]
This has been resolved in https://github.com/nathan-fiscaletti/ts3integration/commit/f44d3036ded8f3e437177d6e7a87a4caaf2fdeda and will be released in the next version of the application. Issue will remain open until the fix has been merged into the master branch and released.

**Comment by nathan-fiscaletti** [comment]
Fixed in version 2.0.7
