### ISSUE TITLE
[FEATURE] Integrating Clubs

### ISSUE THREAD

**Issue by ArxKnight** [nathan-fiscaletti/TeamSpeak-Integration-Issue-Tracker#11]
Hi, I think it would be cool if we could be able to have users joins clubs and then have that club that the user has joined sync up to a Teamspeak group. I am unaware if this is already a feature however if not then it would be great to have.
![index](https://user-images.githubusercontent.com/19707286/72577996-9d31ec80-38cc-11ea-800c-7cd30ae0ee7a.png)

**Comment by nathan-fiscaletti** [comment]
Currently the best alternative to this is to use profile fields exclusively from clubs. 

For example, if each club represents a different game, set up a profile field called "Game" and let users modify it at their whim, then tie that profile field to a teamspeak server group.

**Comment by ArxKnight** [comment]
ok cool, I have set that up. I am having to use a select box but is there any other type of box I could use as the box is very small and hard to control as to select multiple you have to hold down control and then scroll a little and hold control again and select some more, any ideas? - http://prntscr.com/qsjlub

**Comment by nathan-fiscaletti** [comment]
Unfortunately, the application only supports Select Type inputs for profile fields. This is by design, since a select box is the only way to convey "one or multiple" that IPS provides. If you want, you can only allow people to select one profile field value at a time to make the select box more usable.

**Comment by ArxKnight** [comment]
Well I need to make it so people can select mutiaple games

**Comment by ArxKnight** [comment]
Also in the select box when you select multaple boxes the bot just doesn't add you to any groups?

**Comment by nathan-fiscaletti** [comment]
You'll need to leave the select box the way it is i suppose then. Until the application does support integrating clubs into the group association.

**Comment by nathan-fiscaletti** [comment]
And it should add you to any groups you have associations set up for. Assuming you have your TSID set in the settings.

**Comment by ArxKnight** [comment]
when all the games are listed if I select one then it adds me to the group however if I select multaple then it just removes all the groups and leaves it that way

**Comment by ArxKnight** [comment]
The only way I am able to get it to work properly is to make a Profile Field Called "Games I Play" then Make the content the names of the games e.g. "Minecraft" and have a yes or no option (No by default) and set the sync for say if Minecraft = Option "Yes" then Put Tag "Minecraft" on the user.

**Comment by nathan-fiscaletti** [comment]
That shouldn't be necessary. Can you switch back to the multiple select and show me how you have your group associations set up?

**Comment by ArxKnight** [comment]
http://prntscr.com/qsjrrv

http://prntscr.com/qsjzau

http://prntscr.com/qsjv0s

The Small box is kinda not very user-friendly, so it would be better if you could add the functionality to be able to have a yes/no box instead or in addition.

**Comment by LostkingZ** [comment]
http://prntscr.com/qsjv0s

**Comment by LostkingZ** [comment]
Also, it would be cool to be able to set it so if a member has donated then they could recive a tag on the TeamSpeak Server.

**Comment by LostkingZ** [comment]
Found an issue with the Display on users profiles not updating when a user changes channel btw ( Yes I refreshed the page to make sure XD)

**Comment by ArxKnight** [comment]
Hey, any idea when you'll be able to work on implementing this feature? Looking at  your profile you have quite a few projects that your working on already.

**Comment by nathan-fiscaletti** [comment]
Completed in https://github.com/nathan-fiscaletti/ts3integration/commit/f0fc5428492fb17532f7559c0137efa54afcef42
