### ISSUE TITLE
[BUG] Cron Error (Email Spam)

### ISSUE THREAD

**Issue by ArxKnight** [nathan-fiscaletti/TeamSpeak-Integration-Issue-Tracker#12]
**Do you own the TS3 Integration application?**
https://invisioncommunity.com/profile/558110-lostking329/

**Describe the bug**
The Bug is that I keep receving emails from my cron that there is an error, I have contacted both IPS support and my web hosting support and from what they can gather the error is being generated by the TeamSpeak Application. The error is as follows:
 Hi, I am currently receiving a cron error every five minutes, please could you help me with this?

Error in question:

Exception:
Exception Object
(
[message:protected] => DateInterval::__construct(): Unknown or bad format (15)
[string:Exception:private] =>
[code:protected] => 0
[file:protected] => /home/kingbxdt/public_html/system/Task/Task.php
[line:protected] => 401
[trace:Exception:private] => Array
(
[0] => Array
(
[file] => /home/kingbxdt/public_html/system/Task/Task.php
[line] => 401
[function] => __construct
[class] => DateInterval
[type] => ->
[args] => Array
(
[0] => 15
)

)

[1] => Array
(
[file] => /home/kingbxdt/public_html/system/Task/Task.php
[line] => 199
[function] => unlock
[class] => IPS\_Task
[type] => ->
[args] => Array
(
)

)

[2] => Array
(
[file] => /home/kingbxdt/public_html/applications/core/interface/task/task.php
[line] => 54
[function] => queued
[class] => IPS\_Task
[type] => ::
[args] => Array
(
)

)

)

[previous:Exception:private] =>
[severity] => 2
) 

**To Reproduce**
Steps to reproduce the behaviour:
N/A

**Expected behavior**
N/A

**Screenshots**
http://prntscr.com/qrj9vi

**Desktop (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by nathan-fiscaletti** [comment]
This is a known bug so I will keep this issue open until it is resolved. 

For the time being i believe the solution is to disable the "Run as Task" option of the TeamSpeak application and delete the relevant entry from the `core_tasks` table in your database. 

If this does not resolve the issue, please let me know.

I will add this to the next version I release.

**Comment by nathan-fiscaletti** [comment]
Related to https://github.com/nathan-fiscaletti/TeamSpeak-Integration-Issue-Tracker/issues/10

**Comment by nathan-fiscaletti** [comment]
This has been resolved in https://github.com/nathan-fiscaletti/ts3integration/commit/f44d3036ded8f3e437177d6e7a87a4caaf2fdeda and will be released in the next version of the application. Issue will remain open until the fix has been merged into the master branch and released.

**Comment by nathan-fiscaletti** [comment]
Fixed in version 2.0.7
