### ISSUE TITLE
[Help Needed] Server Returns: Connection Refused

### ISSUE THREAD

**Issue by ArxKnight** [nathan-fiscaletti/TeamSpeak-Integration-Issue-Tracker#13]
Do you own the TS3 Integration application?
https://invisioncommunity.com/profile/558110-lostking329/

Describe the bug
The error in question is that I am unable to connect the application to the TeamSpeak Server, I receive this error: "Error while testing connection Error: Server returns: Connection refused, ."

I have spoken to my TeamSpeak hosting and they have whitelisted the IP for the forums however I am still unable to connect the application. any help with this would be much appreciated.

To Reproduce
Steps to reproduce the behaviour:
N/A

Expected behaviour
Application Connects to the TeamSpeak

Screenshots
http://prntscr.com/qrjdlu

Desktop (please complete the following information):
N/A

Additional context
N/A

**Comment by nathan-fiscaletti** [comment]
Unfortunately this is something you will need to resolve with your TeamSpeak hosting company. 

* Ensure that your query port is the one that they have open for query admin.
* Ensure that the query admin username and password are correct

Another thing you can try is to test the connection to the server manually before using the teamspeak application. 

To do this, use the following commands in your command line:
```
telnet <teamspeak-ip> 10011
```

You should see something like this as the output:
```
Trying 11.5.0.1...
Connected to 11.5.0.1.
Escape character is '^]'.
TS3
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.

```

If you are able to connect from the command line, but not from your web server, this means you have an issue with your hosting provider for your forums.

In this case, you will need to have your FORUM hosting provider open an OUTBOUND port and supply the necessary information in the "Bind Address" and "Bind Port" fields in your TeamSpeak application configuration. Find the relevant documentation [here](https://invisioncommunity.com/files/file/9079-teamspeak-integration/)

**Comment by ArxKnight** [comment]
Hi, I have tried using the Telenet command and I am able to get straight into the Teamspeak as shown in this screenshot - http://prntscr.com/qs0uh3 , So I have contacted my TeamSpeak hosting company to ask about the Query Port for the Admin Query being opened. I'll update you when I get a response.

Thank you for your trobleshooting help. :)

Kind Regards,
Alex

**Comment by ArxKnight** [comment]
Hi, I have got a responce from them stating that the port is infact open and it could be something on my web hosting that could be preventing it? any ideas to what that could be?

**Comment by nathan-fiscaletti** [comment]
Read the bottom portion of my previous comment:

> If you are able to connect from the command line, but not from your web server, this means you have an issue with your hosting provider for your forums.
> 
> In this case, you will need to have your FORUM hosting provider open an OUTBOUND port and supply the necessary information in the "Bind Address" and "Bind Port" fields in your TeamSpeak application configuration. Find the relevant documentation here

**Comment by ArxKnight** [comment]
What port would be required to open for the outbound port?

**Comment by ArxKnight** [comment]
Also as a side note since you published the update for the application I can no longer download the application from the store ?
http://prntscr.com/qs1x0x

**Comment by nathan-fiscaletti** [comment]
You should be able to? Are you logged in to the correct account?

![image](https://user-images.githubusercontent.com/1699763/73085882-15804b00-3e95-11ea-85d6-606d4fed5c2a.png)

**Comment by nathan-fiscaletti** [comment]
> What port would be required to open for the outbound port?

I would speak to your forums hosting provider about the instructions listed on the application page, specifically under the "Using with a Cloud Server" part of the instructions.

https://invisioncommunity.com/files/file/9079-teamspeak-integration/

**Comment by ArxKnight** [comment]
ok thank you it's working now, also I am now able to download the update from the posting for the application again somehow :)

**Comment by nathan-fiscaletti** [comment]
Glad everything is working out! Let me know if there is anything else you need. I'm going to close this issue.

**Comment by ArxKnight** [comment]
As you currently don't have a way to link up group syncing with the clubs system on IPS, what do you propose for an alternative for profile fields? as in how would I go about setting them up?

**Comment by nathan-fiscaletti** [comment]
Let's move that discussion to https://github.com/nathan-fiscaletti/TeamSpeak-Integration-Issue-Tracker/issues/11
