### ISSUE TITLE
[BUG] Error: host isn't a ts3 instance!, .

### ISSUE THREAD

**Issue by Parilar** [nathan-fiscaletti/TeamSpeak-Integration-Issue-Tracker#22]
**Do you own the TS3 Integration application?**
https://invisioncommunity.com/profile/591890-parilar/

**Describe the bug**
The error Message "Error: host isn't a ts3 instance!, ." Appears when i opening the settings page

**Invision Community (please complete the following information):**
 - Invision Community Version: 4.4.10
 - TeamSpeak Integration Version: 3.12.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version newest

**Additional context**
Restarting the server solved the issue for ~ 5 minutes

**Comment by Parilar** [comment]
This error seems to be accour only sometimes.

It looks like that the error appears when i change a secondary group of a user und he tries to sync it with the server

**Comment by Parilar** [comment]
I did some test and every time he changes a group on the teamspeak the plugin breaks for 5-10 minutes. If i remove 2 roles on a user the plugin removes 1 group, plugin breaks + 10 min delay, removes second group

**Comment by nathan-fiscaletti** [comment]
It sounds like you don't have your IPS instance white listed on your TeamSpeak server for query commands.

Add the outbound IP address of your IPS server to the `query_ip_whitelist.txt` file on your TeamSpeak 3 server and give it around 15 minutes to update the list (or restart your TeamSpeak server for it to take effect.)

If you are using a cloud based IPS solution, please see the relevant section of the [main application page](https://invisioncommunity.com/files/file/9079-teamspeak-integration/)

**Comment by Parilar** [comment]
Thx that fixxed my problem
