### ISSUE TITLE
[BUG] Admin area app icon alignment issue

### ISSUE THREAD

**Issue by tuuni** [nathan-fiscaletti/TeamSpeak-Integration-Issue-Tracker#7]
**Describe the bug**
Admin area app icon is not aligned correctly. 

Here is the CSS selector:
`#acpAppList [data-tab="tab_ts3integration"] .acpAppList_icon {
    content: url(uploads/set_resources_1/b0cbd88…_teamspeak-brands.svg);
    width: 26px !important;
    height: 26px !important;
    **margin-left: 22px !important**
}`

**Expected behavior**
Remove: margin-left: 22px !important
Replace: margin: auto

**Screenshot**
![image](https://user-images.githubusercontent.com/51503829/65768187-ea7d2900-e138-11e9-82c7-a05dfbf0cd75.png)

**Comment by nathan-fiscaletti** [comment]
What version of ICS are you running? And do you have any custom themes applied to ACP?

**Comment by tuuni** [comment]
I found an issue now.
Spacious ACP app is interfering with your app.

This option creates the problem in ACP plugin:
![image](https://user-images.githubusercontent.com/51503829/65768802-ad199b00-e13a-11e9-948c-f705e5511a76.png)

I turned it off and now there is no alignment issue, but i think if you add margin: auto to that css selector then both apps works without any styling issues.

**Comment by nathan-fiscaletti** [comment]
Have you tested using `margin:auto;` with spacious ACP disabled to make sure that will fix this? If so I'll make a hot fix and add it to the next version.

**Comment by tuuni** [comment]
Yes, i tested it like you asked. It's working fine. "margin: auto" gives equal spacing from left and right, that's one way to center things.

**Comment by nathan-fiscaletti** [comment]
This has been fixed and will be included in the v2.0.7 release.
